version: '3'
services:
  web:
    build: .
    volumes:
      - './:/var/www/html'
    ports:
      - '80:80'
    environment:
      - PHP_MEMORY_LIMIT=1G
      - PHP_DISPLAY_ERRORS=On
      - XDEBUG_REMOTE_AUTOSTART=1
      - XDEBUG_REMOTE_CONNECT_BACK=0
      - XDEBUG_REMOTE_HOST=192.168.1.3
    container_name: ltvplus
